name: Python package

on: [push]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      env: # Or as an environment variable
        SETTINGS_YAML: ${{ secrets.SETTINGS_YAML }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install PyDrive and pillow
      run: |
        pip install PyDrive
        pip install pillow
    - name: Install fonts
      run: |
        cd 1_tool
        ./Add-Font.ps1 -ExecutionPolicy unrestricted ./fonts/GenShinGothic-Heavy.ttf
        ./Add-Font.ps1 -ExecutionPolicy unrestricted ./fonts/rounded-l-mgenplus-2pp-heavy.ttf
        add-type -AssemblyName system.drawing
        (New-Object System.Drawing.Text.InstalledFontCollection).Families
      shell: powershell
    - name: install secure file
      run: |
        echo %SETTINGS_YAML% > settings.yml
      shell: cmd
