name: Python package

on: [push]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install PyDrive and pillow
      run: |
        pip install PyDrive
        pip install pillow
    - name: Install fonts
      run: |
        cd 1_tool
        ./Add-Font.ps1 -ExecutionPolicy unrestricted ./fonts/GenShinGothic-Heavy.ttf
        ./Add-Font.ps1 -ExecutionPolicy unrestricted ./fonts/rounded-l-mgenplus-2pp-heavy.ttf
        add-type -AssemblyName system.drawing
        (New-Object System.Drawing.Text.InstalledFontCollection).Families
      shell: powershell
    - name: Install secure file
      env: # Or as an environment variable
        SETTINGS_YAML: ${{ secrets.SETTINGS_YAML }}
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
      run: |
        python env2file.py
        dir
        type credentials.json
        type settings.yaml
      shell: cmd
    - name: Generate map font
      run: |
        cd 3_map_text
        mkdir out
        python generate.py
        cd out
        dir
    - name: Generate main font copy
      run: |
        cd 2_main_text
        mkdir out
        python generate.py
        cd out
        dir
    - name: Pack mod and upload
      run: |
        python main.py
